//! Architecture-selected normalized CrabEFI Runtime Services image.
//!
//! The files in `images/` are generated by `./crabefi bundle-runtime`. They
//! are kept together with the source revision that produced them so a library
//! consumer can embed a matching runtime image using Cargo alone.

#![no_std]
#![deny(unsafe_code)]

#[cfg(target_arch = "x86_64")]
const IMAGE_BYTES: &[u8] = include_bytes!("../images/x86_64/runtime.img");
#[cfg(target_arch = "x86_64")]
const DIGEST_BYTES: &[u8; 32] = include_bytes!("../images/x86_64/sha256.bin");

#[cfg(target_arch = "aarch64")]
const IMAGE_BYTES: &[u8] = include_bytes!("../images/aarch64/runtime.img");
#[cfg(target_arch = "aarch64")]
const DIGEST_BYTES: &[u8; 32] = include_bytes!("../images/aarch64/sha256.bin");

#[cfg(target_arch = "riscv64")]
const IMAGE_BYTES: &[u8] = include_bytes!("../images/riscv64/runtime.img");
#[cfg(target_arch = "riscv64")]
const DIGEST_BYTES: &[u8; 32] = include_bytes!("../images/riscv64/sha256.bin");

#[cfg(not(any(
    target_arch = "x86_64",
    target_arch = "aarch64",
    target_arch = "riscv64"
)))]
compile_error!("CrabEFI has no bundled Runtime Services image for this architecture");

/// Normalized Runtime Services image for the compilation target.
pub static IMAGE: &[u8] = IMAGE_BYTES;

/// SHA-256 digest of [`IMAGE`].
pub const SHA256: [u8; 32] = *DIGEST_BYTES;

#[cfg(test)]
mod tests {
    use crabefi_runtime_abi::{ValidatedImage, architecture};
    use sha2::{Digest, Sha256};

    fn validate(bytes: &[u8], expected_digest: &[u8; 32], expected_architecture: u16) {
        ValidatedImage::parse(bytes, expected_architecture).expect("valid bundled runtime image");
        let actual: [u8; 32] = Sha256::digest(bytes).into();
        assert_eq!(&actual, expected_digest);
    }

    #[test]
    fn all_bundled_images_are_valid_and_digest_bound() {
        validate(
            include_bytes!("../images/x86_64/runtime.img"),
            include_bytes!("../images/x86_64/sha256.bin"),
            architecture::X86_64,
        );
        validate(
            include_bytes!("../images/aarch64/runtime.img"),
            include_bytes!("../images/aarch64/sha256.bin"),
            architecture::AARCH64,
        );
        validate(
            include_bytes!("../images/riscv64/runtime.img"),
            include_bytes!("../images/riscv64/sha256.bin"),
            architecture::RISCV64,
        );
    }
}
