[package]
name = "crabefi-runtime-image"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0 OR MIT"
build = "build.rs"

[workspace]

[dependencies]
crabefi-efi-types = { path = "../crabefi-efi-types" }
crabefi-runtime-abi = { path = "../crabefi-runtime-abi" }
r-efi = "5.3"
rsa = { version = "0.9", default-features = false }
sha2 = { version = "0.10", default-features = false, features = ["force-soft", "oid"] }
zerocopy = { version = "0.8", default-features = false, features = ["derive"] }

[[bin]]
name = "crabefi-runtime-image"
path = "src/main.rs"
test = true
bench = false

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
codegen-units = 1
opt-level = "s"
strip = false
